//! # Strategy Engine Module (Layer 6)
//!
//! Signal generation from feature vectors, regime-conditioned strategy routing,
//! signal quality scoring, and debouncing. This engine determines when and how
//! to enter/exit trades based on active strategies and current market regime.

use crate::config::QuantConfig;
use crate::error::{QuantError, QuantResult};
use crate::regime::{Regime, RegimeResult};
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use tokio::sync::RwLock;
use tracing::{info, debug, warn};

/// Comparison operator for strategy rules
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum Comparator {
    GreaterThan,
    LessThan,
    EqualTo,
    CrossAbove,
    CrossBelow,
}

/// A single trading rule
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Rule {
    pub feature: String,
    pub operator: Comparator,
    pub threshold: f64,
    pub lookback: u32,
}

/// Position sizing method
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PositionSizingMethod {
    FixedFraction(f64),         // % of account
    Kelly(f64),                 // Kelly criterion fraction
    VolatilityTargeted(f64),    // % volatility target
    Fixed,                      // Fixed lot size
}

/// A trading strategy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Strategy {
    pub id: uuid::Uuid,
    pub name: String,
    pub entry_rules: Vec<Rule>,
    pub exit_rules: Vec<Rule>,
    pub position_sizing: PositionSizingMethod,
    pub max_holding_bars: u32,
    pub regime_filter: Vec<Regime>,
    pub created_at: DateTime<Utc>,
    pub status: StrategyStatus,
    pub performance: StrategyPerformance,
}

/// Strategy lifecycle status
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum StrategyStatus {
    Production,
    PaperTrading,
    Lab,
    Retired,
}

/// Performance tracking for a strategy
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct StrategyPerformance {
    pub total_trades: u32,
    pub winning_trades: u32,
    pub losing_trades: u32,
    pub total_pnl: Decimal,
    pub sharpe_ratio: f64,
    pub sortino_ratio: f64,
    pub max_drawdown_pct: f64,
    pub profit_factor: f64,
    pub win_rate: f64,
    pub avg_holding_bars: f64,
    pub last_updated: Option<DateTime<Utc>>,
}

/// Signal generated by the strategy engine
#[derive(Debug, Clone)]
pub struct TradeSignal {
    pub symbol: String,
    pub direction: TradeSignalDirection,
    pub strength: f64,
    pub strategy_id: uuid::Uuid,
    pub regime: Regime,
    pub feature_snapshot: Vec<f64>,
    pub timestamp: DateTime<Utc>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum TradeSignalDirection {
    Buy,
    Sell,
    Close,
    Hold,
}

/// Strategy engine — routes signals based on regime
#[derive(Debug)]
pub struct StrategyEngine {
    /// All registered strategies, keyed by ID
    strategies: Arc<RwLock<HashMap<uuid::Uuid, Strategy>>>,
    /// Debounce tracking: symbol -> last signal time
    debounce_tracker: Arc<RwLock<HashMap<String, DateTime<Utc>>>>,
    /// Debounce interval
    debounce_seconds: u64,
    /// Minimum signal quality threshold
    min_quality: f64,
}

impl StrategyEngine {
    pub fn new(config: &QuantConfig) -> Self {
        Self {
            strategies: Arc::new(RwLock::new(HashMap::new())),
            debounce_tracker: Arc::new(RwLock::new(HashMap::new())),
            debounce_seconds: config.strategy.signal_debounce_seconds,
            min_quality: config.strategy.min_signal_quality,
        }
    }

    /// Register a new strategy
    pub async fn register_strategy(&self, strategy: Strategy) -> QuantResult<()> {
        let mut strategies = self.strategies.write().await;
        strategies.insert(strategy.id, strategy);
        info!("Registered strategy: {}", strategies.len());
        Ok(())
    }

    /// Evaluate features across all active strategies
    pub async fn evaluate(&self, symbol: &str, features: &[f64], regime: &RegimeResult) -> QuantResult<Option<TradeSignal>> {
        // Check debounce
        {
            let debounce = self.debounce_tracker.read().await;
            if let Some(last_time) = debounce.get(symbol) {
                let elapsed = (Utc::now() - *last_time).num_seconds() as u64;
                if elapsed < self.debounce_seconds {
                    return Ok(None);
                }
            }
        }

        let strategies = self.strategies.read().await;
        let mut best_signal: Option<TradeSignal> = None;
        let mut best_strength = 0.0;

        for strategy in strategies.values() {
            if strategy.status != StrategyStatus::Production {
                continue;
            }

            // Check regime filter
            if !strategy.regime_filter.contains(&regime.dominant_regime) {
                continue;
            }

            // Evaluate entry rules
            if let Some(direction) = self.evaluate_rules(&strategy.entry_rules, features) {
                let signal_quality = self.compute_signal_quality(&strategy, features, regime);
                
                if signal_quality >= self.min_quality && signal_quality > best_strength {
                    best_strength = signal_quality;
                    best_signal = Some(TradeSignal {
                        symbol: symbol.to_string(),
                        direction,
                        strength: signal_quality,
                        strategy_id: strategy.id,
                        regime: regime.dominant_regime.clone(),
                        feature_snapshot: features.to_vec(),
                        timestamp: Utc::now(),
                    });
                }
            }

            // Check exit rules
            if let Some(_) = self.evaluate_rules(&strategy.exit_rules, features) {
                // Close existing position for this symbol
                best_signal = Some(TradeSignal {
                    symbol: symbol.to_string(),
                    direction: TradeSignalDirection::Close,
                    strength: 1.0,
                    strategy_id: strategy.id,
                    regime: regime.dominant_regime.clone(),
                    feature_snapshot: features.to_vec(),
                    timestamp: Utc::now(),
                });
            }
        }

        // Update debounce if we have a signal
        if best_signal.is_some() {
            let mut debounce = self.debounce_tracker.write().await;
            debounce.insert(symbol.to_string(), Utc::now());
        }

        Ok(best_signal)
    }

    /// Evaluate a set of rules against feature values
    fn evaluate_rules(&self, rules: &[Rule], features: &[f64]) -> Option<TradeSignalDirection> {
        if rules.is_empty() {
            return None;
        }

        // Simple weighted voting among rules
        let mut buy_score = 0.0;
        let mut sell_score = 0.0;
        let mut total_weight = 0.0;

        for rule in rules {
            let feature_idx = self.get_feature_index(&rule.feature);
            if feature_idx >= features.len() {
                continue;
            }
            let value = features[feature_idx];
            let weight = 1.0;

            match rule.operator {
                Comparator::GreaterThan => {
                    if value > rule.threshold { buy_score += weight; } else { sell_score += weight; }
                }
                Comparator::LessThan => {
                    if value < rule.threshold { sell_score += weight; } else { buy_score += weight; }
                }
                Comparator::CrossAbove => {
                    // Simplified: just check if value > threshold
                    if value > rule.threshold { buy_score += weight; }
                }
                Comparator::CrossBelow => {
                    if value < rule.threshold { sell_score += weight; }
                }
                Comparator::EqualTo => {
                    if (value - rule.threshold).abs() < 0.001 { buy_score += weight; }
                }
            }
            total_weight += weight;
        }

        if total_weight == 0.0 {
            return None;
        }

        buy_score /= total_weight;
        sell_score /= total_weight;

        if buy_score > 0.6 {
            Some(TradeSignalDirection::Buy)
        } else if sell_score > 0.6 {
            Some(TradeSignalDirection::Sell)
        } else {
            None
        }
    }

    /// Compute signal quality score (0.0 — 1.0)
    fn compute_signal_quality(&self, strategy: &Strategy, features: &[f64], regime: &RegimeResult) -> f64 {
        let mut score = 0.5; // Base score

        // Adjust based on regime confidence
        score += regime.confidence * 0.2;

        // Adjust based on strategy historical performance
        if strategy.performance.total_trades > 0 {
            score += strategy.performance.win_rate * 0.15;
            score += (strategy.performance.sharpe_ratio.min(3.0) / 3.0) * 0.15;
        }

        // Regime adjustment
        score *= regime.dominant_regime.sizing_multiplier();

        score.clamp(0.0, 1.0)
    }

    /// Map feature name to index in feature vector
    fn get_feature_index(&self, name: &str) -> usize {
        let feature_names = [
            "log_return_1", "log_return_5", "ema_12_26_diff", "rsi_14",
            "atr_14", "obv", "roll_mean_20", "roll_std_20",
            "hour_sin", "hour_cos", "hurst_20",
        ];
        feature_names.iter().position(|&n| n == name).unwrap_or(usize::MAX)
    }

    /// Get all active production strategies
    pub async fn get_active_strategies(&self) -> Vec<Strategy> {
        let strategies = self.strategies.read().await;
        strategies.values()
            .filter(|s| s.status == StrategyStatus::Production)
            .cloned()
            .collect()
    }

    /// Update strategy performance after a trade
    pub async fn update_performance(&self, strategy_id: &uuid::Uuid, pnl: Decimal) -> QuantResult<()> {
        let mut strategies = self.strategies.write().await;
        if let Some(strategy) = strategies.get_mut(strategy_id) {
            strategy.performance.total_trades += 1;
            strategy.performance.total_pnl += pnl;
            if pnl > Decimal::ZERO {
                strategy.performance.winning_trades += 1;
            } else {
                strategy.performance.losing_trades += 1;
            }
            strategy.performance.win_rate = strategy.performance.winning_trades as f64
                / strategy.performance.total_trades.max(1) as f64;
            strategy.performance.last_updated = Some(Utc::now());
            Ok(())
        } else {
            Err(QuantError::StrategyError(format!("Strategy {} not found", strategy_id)))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn create_test_strategy() -> Strategy {
        Strategy {
            id: uuid::Uuid::new_v4(),
            name: "Test Strategy".into(),
            entry_rules: vec![
                Rule { feature: "rsi_14".into(), operator: Comparator::LessThan, threshold: 30.0, lookback: 1 },
                Rule { feature: "ema_12_26_diff".into(), operator: Comparator::GreaterThan, threshold: 0.0, lookback: 1 },
            ],
            exit_rules: vec![
                Rule { feature: "rsi_14".into(), operator: Comparator::GreaterThan, threshold: 70.0, lookback: 1 },
            ],
            position_sizing: PositionSizingMethod::FixedFraction(0.01),
            max_holding_bars: 48,
            regime_filter: vec![Regime::TrendingUp],
            created_at: Utc::now(),
            status: StrategyStatus::Production,
            performance: StrategyPerformance::default(),
        }
    }

    #[tokio::test]
    async fn test_strategy_evaluation() {
        let config = QuantConfig::default();
        let engine = StrategyEngine::new(&config);
        let strategy = create_test_strategy();
        engine.register_strategy(strategy).await.unwrap();

        let features = vec![25.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5];
        let regime_result = RegimeResult {
            symbol: "EURUSD".into(), time: Utc::now(),
            probabilities: vec![],
            dominant_regime: Regime::TrendingUp,
            confidence: 0.8,
            is_transition: false,
        };

        let signal = engine.evaluate("EURUSD", &features, &regime_result).await.unwrap();
        assert!(signal.is_some());
    }
}
